### PR TITLE
fix transpose opt bug in opset 10

### PR DESCRIPTION
**Pull request by lucienwang1009**

### CODE REVIEW

**Comment by snnn** [comment]
Does it have effect on any of the mlperf models?

**Comment by guschmue** [comment]
I have tested them on opset-10 earlier this week and they are not impacted.

**Comment by lucienwang1009** [comment]
Thanks @guschmue. We ought to include these mlperf models in our tests.

**Comment by guschmue** [comment]
resnet50, mobilenet and ssd-mobilenet are in the tests already I think.

**Pull request merged**
