### PR TITLE
removed train outputs from bn if they are not connected

### PR DESCRIPTION
**Pull request by guschmue**

### CODE REVIEW

**Comment by pengwa** [comment]
the pylint failed but the error detail page show an 500 response, just re-run the case to see whether it can pass.

**Comment by pengwa** [comment]
@nbcsm  is the 500 internal error for the detail pylint error page known issue? I observed similar  problem for another PR.

**Comment by guschmue** [comment]
yes, can't get to the pylint log either. Local pylint is happy.

**Comment by guschmue** [comment]
now it works again - unrelated change:
```tf2onnx/graph.py:553:12: R1720: Unnecessary "else" after "raise" (no-else-raise)
************* Module tf2onnx.shape_inference
tf2onnx/shape_inference.py:99:12: R1720: Unnecessary "else" after "raise" (no-else-raise)
```
will fix it

**Comment by zhijxu-MS** [comment]
> now it works again - unrelated change:
> tf2onnx/graph.py:553:12: R1720: Unnecessary "else" after "raise" (no-else-raise)
> tf2onnx/shape_inference.py:99:12: R1720: Unnecessary "else" after "raise" (no-else-raise)
> 
> will fix 

I will fix it in my PR.

**Comment by zhijxu-MS** [comment]
> now it works again - unrelated change:
> tf2onnx/graph.py:553:12: R1720: Unnecessary "else" after "raise" (no-else-raise)
> tf2onnx/shape_inference.py:99:12: R1720: Unnecessary "else" after "raise" (no-else-raise)
> will fix
> 
> I will fix it in my PR.
the fix has been merged into master, @guschmue you could rebase and try it again.

**Comment by guschmue** [comment]
thanks

**Pull request merged**
