### PR TITLE
Tom/ort 1.8

### PR DESCRIPTION
**Pull request by TomWildenhain-Microsoft**

### CODE REVIEW

**Review by guschmue — APPROVED** [review]

**Comment by guschmue** [comment]
wired, why did it start to fail?

**Comment by TomWildenhain-Microsoft** [comment]
> wired, why did it start to fail?

I'm not completely sure.  For some reason it is installing flatbuffers 2.0 and that's causing the failure.

**Comment by guschmue** [comment]
onnxruntime installs flatbuffers without pinning. tf2onnx wants flatbuffers~=1.12 - I guess if flatbuffers-2.x is compatible to flatbuffers==1.12 it would explain it.

**Comment by TomWildenhain-Microsoft** [comment]
Hmm, flatbuffers 2.x is compatible with flatbuffers>=1.12 but not flatbuffers~=1.12 so I'm not sure.

**Pull request merged**
