### PR TITLE
changed error

### PR DESCRIPTION
**Pull request by magicse**
changed t2onnx.convert on correct name tf2onnx.convert

### CODE REVIEW

**Review by hwangdeyu — COMMENTED** [review]
Please try to use `git commit -s` command, signed off the commit to fix the DCO error.

**Comment by magicse** [comment]
> Please try to use `git commit -s` command, signed off the commit to fix the DCO error.
ok

**Comment by fatcat-z** [comment]
Could you please fix the DCO issue?

**Review by fatcat-z — APPROVED** [review]
Thanks for your contribution!

**Pull request merged**
