### PR TITLE
Use TFLite Interpreter's public instead of private API to get tensor details

### PR DESCRIPTION
**Pull request by q-ycong-p**
TF-2.12.0 introduced API change that breaks tf2onnx UT tests on the tflite paths, due to the addition of compulsory subgraph arg to several function's input signature:
https://github.com/tensorflow/tensorflow/commit/55d84d7bba942fb4adb552881897c6bbd6e91eef

This commit changes tf2onnx functions that call to TFLite Interpreter class's private `_get_tensor_details`, to instead call its public API `get_tensor_details`. I think the code change is functionality-wise equivalent, from tf2onnx's usage perspective, and circumvent backward comp issue from using a private function.

#2154

### CODE REVIEW

**Comment by q-ycong-p** [comment]
Two naive thoughts I can think of:
- Would it more appropriate to fix upstream at tf so that their API change is backward-comp? For [example](https://github.com/tensorflow/tensorflow/commit/55d84d7bba942fb4adb552881897c6bbd6e91eef#r121433918).
- Looks like tflite Interpreter class's `_get_tensor_details` is a private func. Would it be better to add a public API that guarantees backward-comp in tflite?

**Comment by q-ycong-p** [comment]
Some tests failed during environment setup independent to code diff. How can we rerun the tests without force push?

**Comment by yan12125** [comment]
> How can we rerun the tests without force push?

Close and reopen this PR should work.

**Review by fatcat-z — APPROVED** [review]
This is great! Thanks for your contribution!

**Pull request merged**
