### PR TITLE
Fix no attribute '_captures' issue for Tensorflow 2.13+

### PR DESCRIPTION
**Pull request by guoqingbao**
This issue is related to #2172 and #2180

### CODE REVIEW

**Comment by yan12125** [comment]
Thank you very much for this PR!

There are some pylint errors:
```
************* Module tf2onnx.convert
tf2onnx/convert.py:479:53: C0303: Trailing whitespace (trailing-whitespace)
tf2onnx/convert.py:482:54: C0303: Trailing whitespace (trailing-whitespace)
tf2onnx/convert.py:484:0: C0303: Trailing whitespace (trailing-whitespace)
************* Module tf2onnx.tf_loader
tf2onnx/tf_loader.py:574:57: C0303: Trailing whitespace (trailing-whitespace)
tf2onnx/tf_loader.py:577:58: C0303: Trailing whitespace (trailing-whitespace)
tf2onnx/tf_loader.py:577:29: W0212: Access to a protected member _captures of a client class (protected-access)
```
`trailing-whitespace` is intuitive. For `protected-access`, most likely `# pylint: disable=protected-access` should be added to the line using `_captures` attribute, like what original codes do.

**Comment by guoqingbao** [comment]
> Thank you very much for this PR!
> 
> There are some pylint errors:
> 
> ```
> ************* Module tf2onnx.convert
> tf2onnx/convert.py:479:53: C0303: Trailing whitespace (trailing-whitespace)
> tf2onnx/convert.py:482:54: C0303: Trailing whitespace (trailing-whitespace)
> tf2onnx/convert.py:484:0: C0303: Trailing whitespace (trailing-whitespace)
> ************* Module tf2onnx.tf_loader
> tf2onnx/tf_loader.py:574:57: C0303: Trailing whitespace (trailing-whitespace)
> tf2onnx/tf_loader.py:577:58: C0303: Trailing whitespace (trailing-whitespace)
> tf2onnx/tf_loader.py:577:29: W0212: Access to a protected member _captures of a client class (protected-access)
> ```
> 
> `trailing-whitespace` is intuitive. For `protected-access`, most likely `# pylint: disable=protected-access` should be added to the line using `_captures` attribute, like what original codes do.

I have fixed the pylint warning, please refer to the latest commit.

**Comment by yan12125** [comment]
Thank you. There are still pylint errors about trailing whitespaces. Could you remove them all?

**Comment by guoqingbao** [comment]
> Thank you. There are still pylint errors about trailing whitespaces. Could you remove them all?

I have removed the trailing whitespace, could you help merge this request?

**Comment by yan12125** [comment]
Thank you for the update. I don't have the permission to merge pull requests in this repo. I noticed a maintainer imported changes here to a new pulll request https://github.com/onnx/tensorflow-onnx/pull/2216, so this pull request is probably in scope.

**Review by MODISENEISO — APPROVED** [review]

**Comment by fatcat-z** [comment]
Thanks for your contributions! This will be included in another PR which aims to support the latest version of TensorFlow. Please feel free to close this.

**Comment by guoqingbao** [comment]
> Thanks for your contributions! This will be included in another PR which aims to support the latest version of TensorFlow. Please feel free to close this.

I saw there is a PR that changed "_captures" to "captures" for the latest TensorFlow, but that will not be compatible with the lower version of TensorFlow, right?

**Comment by fatcat-z** [comment]
> > Thanks for your contributions! This will be included in another PR which aims to support the latest version of TensorFlow. Please feel free to close this.
> 
> I saw there is a PR that changed "_captures" to "captures" for the latest TensorFlow, but that will not be compatible with the lower version of TensorFlow, right?

The code in #2216 supports lower versions of TensorFlow as well. The logic is almost as same as yours but your code checks "captures" while that code checks "_captures".

**Comment by guoqingbao** [comment]
> > > Thanks for your contributions! This will be included in another PR which aims to support the latest version of TensorFlow. Please feel free to close this.
> > 
> > 
> > I saw there is a PR that changed "_captures" to "captures" for the latest TensorFlow, but that will not be compatible with the lower version of TensorFlow, right?
> 
> The code in #2216 supports lower versions of TensorFlow as well. The logic is almost as same as yours but your code checks "captures" while that code checks "_captures".

That's great! I come out with this based on the earlier revision.

**Pull request closed without merging**
