### PR TITLE
Support tf ResizeArea op.

### LINKED ISSUE #2239: tf2onnx support for tensorflow Resizing "area" method
Hi,

I had an error message when I tried converting my TensorFlow.Keras model to ONNX format using tf2onnx and ONNX, I realized that the Resizing "area" method used in my model architecture is not supported by ONNX and tf2onnx. I have tried retraining the model using other resizing methods like 'Bilinear' and "Nearest". Neither of them gave me good validation and testing results compared to "Area". I wonder if there is a chance to have tf2onnx support the ResizeArea method for tensorflow.keras.layers.Resizing and tensorflow.image.resize in the future.

image

Thank you,

Zachary Zhao

### PR DESCRIPTION
**Pull request by fatcat-z**
Add support for ResizeArea op, and add tests.
Fix #2239

### CODE REVIEW

**Review by xiaowuhu — APPROVED** [review]

**Comment by ZachZhao96** [comment]
Thank you very much. So, does the current version on the PyPI support the ResizeArea after this commit got merged? or do I expect to see the area method support in the next release?

**Comment by fatcat-z** [comment]
> Thank you very much. So, does the current version on the PyPI support the ResizeArea after this commit got merged? or do I expect to see the area method support in the next release?

This commit has been merged and will be available in next release which is not in a plan yet. If you want this function, you can [install from source](https://github.com/onnx/tensorflow-onnx#build-and-install-latest-from-source-for-development) for your local usage.

**Comment by ZachZhao96** [comment]
> > Thank you very much. So, does the current version on the PyPI support the ResizeArea after this commit got merged? or do I expect to see the area method support in the next release?
> 
> This commit has been merged and will be available in next release which is not in a plan yet. If you want this function, you can [install from source](https://github.com/onnx/tensorflow-onnx#build-and-install-latest-from-source-for-development) for your local usage.

I successfully converted my model to onnx using the new version, but when using onnxruntime for inference, the prediction result is way off compared to the result from the regular keras model.predict. I guess I will have to wait for onnx or onnxruntime to have the ResizeArea method in Resize operation as well. Look forward to the next release. Really appreciate your time.

**Comment by fatcat-z** [comment]
No, resize_area is not an ONNX op.

**Comment by ZachZhao96** [comment]
Thanks, I also tried **resized_spectrogram = tf.image.resize(spectrogram, [256, 256],method = "bilinear", antialias = True),** then I got this error:
image

I wonder if the antialias supported in Resize Op is the same as the tf.image.resize(..., antialias = True).
image

**Pull request merged**
