### PR TITLE
Fix TF1-Keras Dilated Conv ONNX Exported

### PR DESCRIPTION
**Pull request by leimao**
Fix issue #1728.

### CODE REVIEW

**Comment by leimao** [comment]
> Code looks great, really appreciate the unit tests. I'm thinking we probably aren't going to want every company that touches the file appending legal notices. I'll check what our policy is. Are you sure NVIDIA requires those for open source?

Thank you @TomWildenhain-Microsoft. NVIDIA open source process requires me to add those headers. However, if it violates the Contributor License Agreement (CLA), we can remove them.

**Comment by leimao** [comment]
@prasanthpul Please let me know and I believe similar things might also happen in the future. (I may make some other merge request to the repo again.)

**Comment by leimao** [comment]
@TomWildenhain-Microsoft When is the next tf2onnx release? I just want to make sure that this PR does not miss the release. Thank you.

**Comment by leimao** [comment]
@TomWildenhain-Microsoft The NVIDIA license header has been removed. Please review again. Thank you very much.

**Comment by leimao** [comment]
@TomWildenhain-Microsoft After rebasing to the master branch and run CI tests again, I got many weird errors which did not seem to be related to my patch. Could you please give some insights here? Thank you.

**Comment by guschmue** [comment]
took a quick look - some issue with tf-2.6.1 that was released yesterday I think.
Going to take a look later today.

**Comment by leimao** [comment]
> took a quick look - some issue with tf-2.6.1 that was released yesterday I think. Going to take a look later today.

Thank you very much. Please do let me know if there is any action item from my side.

**Comment by guschmue** [comment]
I think it fails now mostly tf-2.6 which should be fixed with my change. Some tf-2.5 ut fails with lstm errors.

**Comment by leimao** [comment]
> I think it fails now mostly tf-2.6 which should be fixed with my change. Some tf-2.5 ut fails with lstm errors.

My pull request has nothing to do with LSTM unless the LSTM uses dilated Conv which is very less likely. Let's merge your pull request on the TF versions for CI to see what will happen.

**Comment by guschmue** [comment]
They released tf-2.5 as tf-2.5.2 nov-1 so maybe it is the same problem like tf-2.6 but I don't understand why my PR passed.

**Comment by leimao** [comment]
> They released tf-2.5 as tf-2.5.2 nov-1 so maybe it is the same problem like tf-2.6 but I don't understand why my PR passed.

I am not a CI expert. Is it even possible to run CI tests locally?

**Comment by leimao** [comment]
@TomWildenhain-Microsoft It seems that there are CI test failings unrelated to this pull request.

**Comment by leimao** [comment]
@TomWildenhain-Microsoft It seems that the CI is downloading models from an invalid URL.
https://github.com/onnx/tensorflow-onnx/blob/03c643a3d482dd44c0a892a780f72207451698f1/tests/run_pretrained_models.yaml#L574
It seems that you guys are using fragile URLs in the repo which is not best practice.

**Comment by leimao** [comment]
@TomWildenhain-Microsoft It seems that this time the CI works as expected.

**Review by TomWildenhain-Microsoft — APPROVED** [review]

**Pull request merged**
