### PR TITLE
make convolution work in any dimensionality

### LINKED ISSUE #461: Cann't support 3d convolution: ValueError: kernel rank must be 2* spatial
3D convolution kernel rank is 5, 3D convolution kernel shape [H, W, D, inChannels, outChannels]
conv_kernel_shape and conv_dims_attr only support kernel rank 2 or 4.

### PR DESCRIPTION
**Pull request by gerbenvv**
Fixes #461.

### CODE REVIEW

**Comment by guschmue** [comment]
super, we definitely want this. Should find some time later today to look at it.

**Comment by guschmue** [comment]
not forgotten to review, just need to find some time.

**Comment by gerbenvv** [comment]
@guschmue Can you review this? It has been open for more than 3 weeks now.

**Comment by guschmue** [comment]
Yes, sorry for being slow on it. I'll do it over the weekend.

**Comment by guschmue** [comment]
Thanks @gerbenvv, looks great!

**Pull request merged**
