### PR TITLE
substitute variable-related ops

### PR DESCRIPTION
**Pull request by lucienwang1009**
#77

### CODE REVIEW

**Comment by lucienwang1009** [comment]
This PR only handles the case where variable-related ops' value depends on the referenced op:
image
In the graph above, Assign update Variable's value after the value is read. So the Assign doesn't affect the final result.
However, there are a lot of more complex cases this PR cannot cover. For instance, if Assign is independent on the referenced op (see the graph below), the Variable's value should be set before flowing down into Add op. In this case, substituting Assign op with Identity will definitely lead to a wrong result.
image

**Comment by nbcsm** [comment]
if a variable is UPDATED in the inference part of a TF graph, then there is NO guarantee the frozen TF graph will behave exactly the same as the original TF graph. (variable is converted to const, not stateful anymore)

and even we can parse a TF training graph directly, there is still nothing we can do, because there is no variable concept in onnx, tensors are stateless...

so i think we should:
- **always let the converter fail on such case by default**, give meaningful message to explain why and let user to modify his graph to avoid such variable usage.
we may do this check at very early stage.

- provide an option to enable substitute_variable_related_ops
but need to print **VERY conspicuous warning message** to let user know the graph may not behave like what they want.
but i am wondering do we really need to support this?

@guschmue for comments.

**Comment by nbcsm** [comment]
We may need to take a look at the usage.
If it is created explicitly by the user script, we do support it.
If it is from some common tf api, we can evaluate whether it is safe to update the graph.

**Comment by nbcsm** [comment]
after discussion, we decided to NOT support this feature for now.
user should avoid to use variables in their script. 
close this pr.

**Pull request closed without merging**
