### PR TITLE
Fix problem with adding more than one tf.newaxis at the same time

### PR DESCRIPTION
**Pull request by southfreebird**
This PR should solve a problem described in the issue: https://github.com/onnx/tensorflow-onnx/issues/1849

### CODE REVIEW

**Comment by fatcat-z** [comment]
Please check the CI failures. Probably you should limit the min opset version for 2 test cases you added.

**Comment by southfreebird** [comment]
It seems something wrong with python3.9 tests

**Comment by southfreebird** [comment]
@fatcat-z 
Could you help with tests please?
It seems something wrong with test_random_std_normal in python3.9 environment

**Comment by fatcat-z** [comment]
> @fatcat-z Could you help with tests please? It seems something wrong with test_random_std_normal in python3.9 environment

Looking into it.

**Review by fatcat-z — APPROVED** [review]
LGTM, thanks for your contribution!

**Pull request merged**
