### PR TITLE
Resize align corners attribute

### PR DESCRIPTION
**Pull request by NikolasMarkou**
align_corners value for coordinate_transformation_mode was never set

### CODE REVIEW

**Comment by NikolasMarkou** [comment]
@guschmue

**Review by TomWildenhain-Microsoft — CHANGES_REQUESTED** [review]
Looks good!  But please remove VERSION_NUMBER and version.py from the commits.

**Comment by NikolasMarkou** [comment]
@TomWildenhain-Microsoft removed

**Review by TomWildenhain-Microsoft — APPROVED** [review]

**Pull request merged**
