### PR TITLE
Handle Mul as Square in TransposeOptimizer

### PR DESCRIPTION
**Pull request by mateusztabaka**
Signed-off-by: Mateusz Tabaka <mateusz.tabaka@intel.com>

### CODE REVIEW

**Comment by mateusztabaka** [comment]
@TomWildenhain-Microsoft please review

**Review by TomWildenhain-Microsoft — APPROVED** [review]

**Comment by TomWildenhain-Microsoft** [comment]
@mateusztabaka thanks for the improvements to transpose optimization!  Is there a particular model you are trying to improve performance on?

**Comment by mateusztabaka** [comment]
There are couple of models I'm working on, but unfortunately I can't share the details.

**Comment by TomWildenhain-Microsoft** [comment]
No problem.  If you are trying to improve perf, you might find this profiling tool useful: 
https://github.com/microsoft/onnxconverter-common/blob/4f4940d8e23c996dc16245d1b9747956ff61e9a0/onnxconverter_common/perfstats.py

**Comment by mateusztabaka** [comment]
Thanks. I will try it out.

**Pull request merged**
