### PR TITLE
Fix the Broken CI

### PR DESCRIPTION
**Pull request by leimao**
1. Fixed the fragile URLs used for CI testing.
2. Fixed the exception handling for `tensorflow_text` import failings.
3. Try TF 2.6.2.

### CODE REVIEW

**Comment by leimao** [comment]
@TomWildenhain-Microsoft There is [another bug](https://dev.azure.com/tensorflow-onnx/tensorflow-onnx/_build/results?buildId=15953&view=logs&j=5b286dbc-2f2d-501c-f60f-3c98ecbd1849&t=e743ef61-2125-5ab4-0b12-241a3b88c22d&l=715) in the CI which prevented this merge request to be merged.

**Comment by leimao** [comment]
@TomWildenhain-Microsoft The other import bug has been found and fixed.

**Comment by leimao** [comment]
@TomWildenhain-Microsoft This merge request should fix the CI test problem. Please review and approve. Thank you.

**Review by guschmue — APPROVED** [review]

**Comment by guschmue** [comment]
Super, thanks!

**Comment by guschmue** [comment]
I think the root cause is that tensorflow 2.6.[01] does not pin its own sub modules to the exact version (like 2.6.1 pulled in the 2.6.0 estimator) and some when they released the patch it must have some incompatible change.
They also released tf-2.7 yesterday, need to add this to the ci pipeline as well.

**Pull request merged**
