### PR TITLE
CI: upgrade onnxruntime to 0.2.1

### PR DESCRIPTION
**Pull request by nbcsm**
upgrade onnxruntime to 0.2.1

### CODE REVIEW

**Comment by pengwa** [comment]
do you want to enable those skipped cases as well, or do that in another PR?

**Comment by nbcsm** [comment]
later in another PR, may also refactor test filter a little bit.

**Comment by pengwa** [comment]
@nbcsm  cool!

**Comment by nbcsm** [comment]
thanks for the review.

**Pull request merged**
