### PR TITLE
L2_NORMALIZATION support for tflite

### PR DESCRIPTION
**Pull request by shesung**

### CODE REVIEW

**Review by hwangdeyu — COMMENTED** [review]
Thanks for contribution!
Please sign off every commit message following [DCO required](https://github.com/onnx/tensorflow-onnx/pull/1989/checks?check_run_id=7145415255).

Signed-off-by: Author Name <authoremail@example.com>

**Comment by shesung** [comment]
sign-off message is added.

**Review by hwangdeyu — APPROVED** [review]
LGTM, thanks!
By the way, are you using any model need this op?

**Comment by shesung** [comment]
This op is used when converting knift model: https://github.com/google/mediapipe/blob/master/mediapipe/models/knift_float.tflite

**Pull request merged**
