### PR TITLE
#1749: Fix fused_batch_norm 5d NDHWC input reshape convert

### PR DESCRIPTION
**Pull request by hwangdeyu**
Co-authored-by: hwangdeyu <dejack953@outlook.com>

fix for #1749

### CODE REVIEW

**Comment by guschmue** [comment]
Looks like tf-1.x does not support NDHWC. You could add a 
```
@check_tf_min_version("2.0", ...)
```
in front of the test.

```
ValueError: Attr 'data_format' of 'FusedBatchNorm' Op passed string 'NDHWC' not in: "NHWC", "NCHW".
```

**Comment by hwangdeyu** [comment]
> Looks like tf-1.x does not support NDHWC. You could add a
> 
> ```
> @check_tf_min_version("2.0", ...)
> ```
> 
> in front of the test.
> 
> ```
> ValueError: Attr 'data_format' of 'FusedBatchNorm' Op passed string 'NDHWC' not in: "NHWC", "NCHW".
> ```

That's right. Thank you @guschmue

**Review by TomWildenhain-Microsoft — APPROVED** [review]

**Comment by garymm** [comment]
Tip to save you some time: In the future replace `fix for #1749` with `Fixes #1749` and GitHub will automatically close the issue when the PR is merged.

**Comment by hwangdeyu** [comment]
> Tip to save you some time: In the future replace `fix for #1749` with `Fixes #1749` and GitHub will automatically close the issue when the PR is merged.

Thanks, very helpful tip. Several key words could be used [Linking a pull request to an issue using a keyword](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

**Pull request merged**
