### PR TITLE
fix bug in utils.get_shape

### PR DESCRIPTION
**Pull request by nbcsm**

### CODE REVIEW

**Comment by pengwa** [comment]
add @guschmue  might have better knowledge for this code. I am curious whether  "shape[0]" possibly be None. :)

**Comment by nbcsm** [comment]
a placeholder with partial shape specified?

**Comment by guschmue** [comment]
This is really old code from the time before we figured that it is better to just use the shapes from shape inference ... not sure if we depend anywhere on this info today (that is why there is this FIXME comment on this method).
The ultimate fix would be to remove the method completely.
At a minimum I'd fix it by removing the ```if``` because setting it to 1 is iffy (this if must be some old crime where we could not deal with known dims).

**Comment by nbcsm** [comment]
anyway, feel free to merge or abandon this pr.

**Comment by pengwa** [comment]
I think the change is ok. let's refine this later. @guschmue  let me know if you have concerns here.

**Pull request merged**
