### PR TITLE
tf-2.6.0 -> tf-2.6.1 to avoid build issues

### PR DESCRIPTION
**Pull request by guschmue**
Signed-off-by: Guenther Schmuelling <guschmue@microsoft.com>

### CODE REVIEW

**Comment by guschmue** [comment]
problem that this PR fixes is that we pinned to tf-2.6.0 and when tf-2.6.1 was released tf-2.6.0, some of the submodules are pulled as tf-2.6.1 which broke our ci.

**Comment by leimao** [comment]
@guschmue Thank you.

**Review by leimao — COMMENTED** [review]
Based on my CI tests, it seems that TF 2.5.0 also has some issues?
https://dev.azure.com/tensorflow-onnx/tensorflow-onnx/_build/results?buildId=15917&view=logs&j=1e6a3963-0640-5ed5-5688-e7a2c88df1bc&t=b1f6dc66-c9aa-58f9-a8c6-6056255c87fd

**Comment by guschmue** [comment]
In your ci/setup step I can see that we are pip installing tf-2.5 but end up with tf-2.6.1 for some reason. Might be a fluke - I let me re-run the failed tests for your and see if it will pass now.

**Comment by leimao** [comment]
@TomWildenhain-Microsoft Could you please review and approve this? Thank you.

**Review by TomWildenhain-Microsoft — APPROVED** [review]

**Comment by leimao** [comment]
@TomWildenhain-Microsoft In fact that there are many CI errors for this merge request. But the GitHub interface failed to show them. We thought this merge quest fixed everything but it did not.

Please see:
https://dev.azure.com/tensorflow-onnx/tensorflow-onnx/_build/results?buildId=15941&view=results

**Pull request merged**
