### PR TITLE
Added support for AddV2 op

### PR DESCRIPTION
**Pull request by djb15**

### CODE REVIEW

**Comment by djb15** [comment]
Tried to sign the CLA multiple times over the weekend and it says I've successfully signed it, although it doesn't reflect here.  Let me know when/if I can try again

**Comment by guschmue** [comment]
I think the cla tool goes through all commits and wants those users agree.
There is one commit from dirkbrink that is different than your github id.

**Comment by djb15** [comment]
Ah that sorted it, thanks!

**Comment by guschmue** [comment]
thanks !!!

**Pull request merged**
